// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCH06piiXw1z4HoEEy4W_-nRCo9m2sJHs',
    appId: '1:1003973879556:web:429f95462b005efc339251',
    messagingSenderId: '1003973879556',
    projectId: 'capstone-2e143',
    authDomain: 'capstone-2e143.firebaseapp.com',
    storageBucket: 'capstone-2e143.firebasestorage.app',
    measurementId: 'G-SZBPPGW05Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6_w64WWvCY8NDKdCYIa7GtCmjHyMzUE',
    appId: '1:1003973879556:android:fd00644be7109a99339251',
    messagingSenderId: '1003973879556',
    projectId: 'capstone-2e143',
    storageBucket: 'capstone-2e143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5PejkxUyrF_tB8IedrvXwQ_2h1suzhI',
    appId: '1:1003973879556:ios:7d00cac3221dafc5339251',
    messagingSenderId: '1003973879556',
    projectId: 'capstone-2e143',
    storageBucket: 'capstone-2e143.firebasestorage.app',
    iosBundleId: 'com.example.cookitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX5PejkxUyrF_tB8IedrvXwQ_2h1suzhI',
    appId: '1:1003973879556:ios:7d00cac3221dafc5339251',
    messagingSenderId: '1003973879556',
    projectId: 'capstone-2e143',
    storageBucket: 'capstone-2e143.firebasestorage.app',
    iosBundleId: 'com.example.cookitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCH06piiXw1z4HoEEy4W_-nRCo9m2sJHs',
    appId: '1:1003973879556:web:227ebf2189a075d7339251',
    messagingSenderId: '1003973879556',
    projectId: 'capstone-2e143',
    authDomain: 'capstone-2e143.firebaseapp.com',
    storageBucket: 'capstone-2e143.firebasestorage.app',
    measurementId: 'G-8MB3PC1T2V',
  );
}
